# Storage method configuration
# Konfiguration der Speichermethode
# Possible values: local (sqlite), database (mysql)
# Mögliche Werte: local (sqlite), database (mysql)
storage-method: local

# MySQL database configuration
# MySQL-Datenbankkonfiguration
mysql:
  host: localhost  # Database host / Datenbank-Host
  port: 3306       # Database port / Datenbank-Port
  database: ultimate_moderation  # Database name / Datenbankname
  username: root  # Database username / Datenbank-Benutzername
  password: root  # Database password / Datenbank-Passwort

discord:
  staff-chat-url: "" # URL for the staff chat webhook, leave empty to disable / URL für den Webhook des Team-Chats, leer lassen um zu deaktivieren